<a href="https://colab.research.google.com/github/irohit373/DS/blob/main/Numpy_Handout.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color='orange'>NumPy</font>

NumPy is a fundamental package for scientific computing in Python, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Important differences between NumPy arrays and the standard Python sequences:<br>
* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size
of an ndarray will create a new array and delete the original.
* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in
memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays
of different sized elements.
* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically,
such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

# <font color='orange'>Why is NumPy Fast?</font>

Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of
course, just “behind the scenes” in optimized, pre-compiled C code. Vectorized code has many advantages, among which
are:
* vectorized code is more concise and easier to read
* fewer lines of code generally means fewer bugs
* the code more closely resembles standard mathematical notation (making it easier, typically, to correctly code
mathematical constructs)
* vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient
and difficult to read for loops.

We will only learn the basics of NumPy, to get started we need to install it!

## <font color='orange'>Installation Instructions</font>

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy

**If you wish to install NumPY using pip, then use the following command:**

    pip install numpy

**Also when using pip, it’s good practice to use a virtual environment.**

## <font color='orange'> Using NumPy</font>

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

In [ ]:
jaggi.ones(3)

array([1., 1., 1.])

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors, arrays, matrices, and number generation. Let's start by discussing arrays.

# <font color='orange'>Numpy Arrays</font>

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the
same type, indexed by a tuple of non-negative integers.<br>
NumPy arrays are the main way we will use Numpy throughout the machine learning notebooks. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).
<img src = 'images/numpy_arrays.png'>
Let's begin our introduction by exploring how to create NumPy arrays.

## <font color='orange'> Creating NumPy Arrays</font>

### <font color='orange'> From a Python List</font>

We can create an array by directly converting a list or list of lists:

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [7, 8, 9]]

In [ ]:
my_matrix_to_array = np.array(my_matrix)

In [ ]:
my_matrix_to_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [ ]:
my_matrix_to_array.shape

(4, 3)

In [ ]:
arr = np.array([1,2,3,4, 'numpy'])
arr

array(['1', '2', '3', '4', 'numpy'], dtype='<U21')

For reference: https://numpy.org/doc/stable/reference/arrays.dtypes.html
(various dtypes explained)

### <font color='orange'> Built-in Methods </font>

There are lots of built-in ways to generate Arrays

### arange()

Return evenly spaced values within a given interval.

In [ ]:
np.arange(start = 0, stop = 10, step = 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(start = 0, stop = 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(start = 0.2, stop = 1, step = 0.3)

array([0.2, 0.5, 0.8])

### zeros() and ones()

Generate arrays of zeros or ones

In [ ]:
np.zeros(shape = 3)

array([0., 0., 0.])

In [ ]:
np.zeros(shape = (5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape = 3)

array([1., 1., 1.])

In [ ]:
np.ones(shape = (3, 3,3,3))

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

### linspace()
Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(start = 0, stop = 10, num = 3) # num - total samples to be generated

array([ 0.,  5., 10.])

In [ ]:
np.linspace(start = 1, stop = 10, num = 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(start = 0, stop = 10, num = 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye()

Creates an identity matrix

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## <font color='orange'> Random</font>

Numpy also has lots of ways to create random number arrays:

**Rand:** Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

**Randn:** The numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution.

**Randint:** Return random integers from low (inclusive) to high (exclusive).

### rand()
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [ ]:
np.random.rand(2)

array([0.73374344, 0.59130311])

In [ ]:
np.random.rand(5, 5)

array([[0.09695787, 0.95143608, 0.98746129, 0.78979923, 0.21183684],
       [0.71058675, 0.49540675, 0.99048615, 0.21467602, 0.12139284],
       [0.56211013, 0.9585283 , 0.84864934, 0.35980196, 0.12600049],
       [0.00987596, 0.06668954, 0.34195606, 0.61106006, 0.42603632],
       [0.06486484, 0.29591474, 0.93125063, 0.84780738, 0.62332959]])

### randn()

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(2)

array([-1.15456343, -1.31990043])

In [ ]:
np.random.randn(5, 5)

array([[ 0.59020851,  0.36908747,  0.23874254,  0.46682798, -1.30725266],
       [-1.34484077, -0.98983351,  0.78376254,  0.90194546,  1.53700523],
       [ 1.75647716, -0.09972414,  0.78326666, -0.46382093,  0.1590618 ],
       [-1.85231124,  0.74944619, -0.46004105, -0.20495004,  0.13049828],
       [-0.76476491,  0.66410314,  0.62844001,  1.15901477,  0.68816542]])

### randint()
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(low = 1, high = 100)

85

In [ ]:
np.random.randint(low = 1, high = 100, size = 10)

array([89, 21, 18, 38, 73, 61, 74, 92, 91, 12])

### normal()

Draw random samples from a normal (Gaussian) distribution.


In [ ]:
np.random.normal(loc=5, scale=4, size=(5, 4))   # loc - mean, scale-variance

array([[ 3.30986019,  4.32249873,  2.03839881,  5.34839009],
       [ 2.99917733,  7.33212247, 10.29612288,  3.28448432],
       [ 3.52935917,  9.89123626,  1.28294926,  4.41398531],
       [-0.97240953,  5.79279971,  7.3291848 ,  3.68242357],
       [ 0.69049584,  4.47087627,  3.03873458,  3.26891882]])

## <font color='orange'> Array Attributes and Methods </font>

Let's discuss some useful attributes and methods of an array:

### ndarray.ndim


**ndim** represents the number of dimensions (axes) of the ndarray.


In [ ]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

array.ndim  # 2 D array

2

In [ ]:
array.shape

(3, 3)

### ndarray.shape

shape is a tuple of integers representing the size of the ndarray in each dimension.

In [ ]:
array.shape

(3, 3)

### ndarray.size

size is the total number of elements in the ndarray. It is equal to the product of elements of the shape.

In [ ]:
array.size

9

### ndarray.dtype

dtype tells the data type of the elements of a NumPy array.

In [ ]:
array.dtype

dtype('int64')

### ndarray.reshape

Gives a new shape to an array without changing its data.

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr1 = arr.reshape(5,5)
arr1.shape

(5, 5)

In [ ]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr1.ndim

2

In [ ]:
# Notice the two sets of brackets [list]
arr1.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1, 20).shape

ValueError: cannot reshape array of size 25 into shape (1,20)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25, 1).shape

(25, 1)

# <font color='orange'> NumPy Indexing and Selection</font>

Now, we will discuss how to select elements or groups of elements from an array.

But before that, let's understand what is postive and negative indexing in a 1D array with the help of a diagram.

<img src = 'images/arr_indexing.png'>

In [ ]:
my_list = [10,20,30,40]
my_list[3]

40

In [ ]:
my_list = [[10,20,30,40]]
my_list[0]

[10, 20, 30, 40]

In [ ]:
# Creating sample array
arr = np.arange(start = 7, stop = 15)
arr

## <font color='orange'> Indexing a 1D array </font>
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# get a value at an index
arr[3]

3

In [ ]:
# get values in a range using positive indexing
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
# get values in a range using negative indexing
arr[-7:-3]

array([18, 19, 20, 21])

## <font color='orange'> Indexing a 2D array (matrices) </font>

The general format is **arr_2d[row][col]** or **arr_2d[row, col]**. I recommend usually using the comma notation for clarity.

<img src='images/arr2d_indexing.png'>

In [ ]:
arr_2d = np.array([[11, 13, 15, 17, 19],
                   [21, 23, 25, 27, 29],
                   [31, 33, 35, 37, 39],
                   [41, 43, 45, 47, 49],
                   [51, 53, 55, 57, 59]])
arr_2d

array([[11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59]])

In [ ]:
# Indexing a row
arr_2d[3]

array([41, 43, 45, 47, 49])

In [ ]:
# Indexing a column
arr_2d[:, 3]

array([17, 27, 37, 47, 57])

In [ ]:
# Getting individual element value
arr_2d[2][4]

39

In [ ]:
arr_2d.shape

(5, 5)

In [ ]:
# 2D array slicing
# Shape (2,4) from top right corner

arr_2d[:2, 1:]

array([[13, 15, 17, 19],
       [23, 25, 27, 29]])

In [ ]:
arr_2d[1][2]

25

In [ ]:
# Modifying individual element value
arr_2d[1][2] = 40

print(arr_2d)

[[11 13 15 17 19]
 [21 23 40 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]]


## <font color='orange'> Broadcasting </font>

Numpy arrays differ from a normal Python list because of their ability to broadcast:

<img src='images/broadcasting.png'>

In [ ]:
arr1 = np.ones(shape=(3, 3))
arr2 = np.arange(3)

print("Array1: ")
print(arr1)
print()
print("Array2: ")
print(arr2)
print()
print("Sum")
print(arr1 + arr2)

Array1: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array2: 
[0 1 2]

Sum
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
arr1 = np.ones(shape=(3, 3))
arr2 = np.arange(3)


In [ ]:
arr2 = np.array([[0],[1],[2]])

In [ ]:
# arr2 = np.ones(shape=(1,3))

In [ ]:
arr2

array([[0],
       [1],
       [2]])

In [ ]:
print(arr1 + arr2)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


## <font color='orange'> Selection </font>

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(start = 1, stop = 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr > 4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# <font color='orange'> NumPy Operations </font>

## <font color='orange'> Arithmetic </font>

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [ ]:
arr1 = np.random.randint(low=0, high=20, size=10)
arr2 = np.random.randint(low=20, high=40, size=10)
print("Array1: ")
print(arr1)
print()
print("Array2: ")
print(arr2)

Array1: 
[19 13 11  0 11 16  3 13  4 14]

Array2: 
[34 26 39 28 38 30 30 22 29 32]


In [ ]:
arr1 + arr2

array([53, 39, 50, 28, 49, 46, 33, 35, 33, 46])

In [ ]:
arr1 * arr2

array([646, 338, 429,   0, 418, 480,  90, 286, 116, 448])

In [ ]:
arr2 - arr1

array([15, 13, 28, 28, 27, 14, 27,  9, 25, 18])

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with infinity
arr2/arr1

<ipython-input-105-e0a7ed40abd1>:3: RuntimeWarning: divide by zero encountered in divide
  arr2/arr1


array([ 1.78947368,  2.        ,  3.54545455,         inf,  3.45454545,
        1.875     , 10.        ,  1.69230769,  7.25      ,  2.28571429])

## <font color='orange'> Universal Array Functions </font>

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

### numpy.max()
Return the maximum of an array or maximum along an axis.

In [ ]:
arr = np.array([5, 8, 9])
np.max(arr)

9

In [ ]:
arr

array([[ 5,  8,  9],
       [ 2,  6, 15]])

In [ ]:
arr = np.array([[5, 8, 9],
                [2, 6, 15]])
np.max(arr, axis= 0)

array([ 5,  8, 15])

In [ ]:
np.max(arr, axis= 1)

array([ 9, 15])

### numpy.min()
Return the minimum of an array or minimum along an axis.

In [ ]:
arr = np.array([[5, 8, 9],[2, 6, 15]])
np.min(arr)

2

In [ ]:
arr = np.array([[5, 8, 9],
                [2, 6, 15]])
np.min(arr, axis= 0)

array([2, 6, 9])

In [ ]:
np.min(arr, axis= 1)

array([5, 2])

### numpy.maximum()
Element-wise maximum of array elements.

In [ ]:
arr1 = np.array([2, 3, 4])
arr2 = np.array([1, 5, 2])
np.maximum(arr1, arr2)

array([2, 5, 4])

### numpy.minimum()
Element-wise minimum of array elements.

In [ ]:
arr1 = np.array([2, 3, 4])
arr2 = np.array([1, 5, 2])
np.minimum(arr1, arr2)

array([1, 3, 2])

### numpy.argmax()
Returns the indices of the maximum values along an axis.

In [ ]:
arr = np.array([4, 8, 9, 14, 2])

np.argmax(arr)

3

In [ ]:
arr = np.array([[10, 14, 12],
                [13, 11, 15]])

np.argmax(arr, axis = 0)

array([1, 0, 1])

### numpy.argmin()
Returns the indices of the minimum values along an axis.

In [ ]:
arr = np.array([4, 8, 9, 14, 2])

np.argmin(arr)

4

In [ ]:
arr = np.array([[10, 14, 12],
               [13, 11, 15]])

np.argmin(arr, axis = 0)

array([0, 1, 0])

In [ ]:
np.argmin(arr, axis = 1)

array([0, 1])

### numpy.sum()
Sum of array elements over a given axis.

In [ ]:
arr = np.array([[5, 7, 9],
                [4, 8, 12]])

np.sum(arr, axis = 0)

In [ ]:
np.sum(arr, axis = 1)

### numpy.mean()
Compute the arithmetic mean along the specified axis.

In [ ]:
arr = np.array([[5, 7, 9],
                [4, 8, 12]])

np.mean(arr, axis = 0)

In [ ]:
np.mean(arr, axis = 1)

### numpy.prod()
Return the product of array elements over a given axis.

In [ ]:
arr1 = np.array([6,2,3])
print(np.prod(arr1))

In [ ]:
arr = np.array([[1., 2.],
                [3., 4.]])

np.prod(arr, axis=1)

### numpy.sqrt()
Return the non-negative square-root of an array, element-wise.

In [ ]:
arr = np.array([4, 36, 12, 49])
np.sqrt(arr)

### numpy.exp()
Calculate the exponential of all elements in the input array.

In [ ]:
np.exp(arr)

### numpy.sin()
Trigonometric sine, element-wise.

In [ ]:
np.sin(arr)

### numpy.log()
Natural logarithm, element-wise.

In [ ]:
arr = np.array([2.3, 4.5, 6])
np.log(arr)

### numpy.floor
Return the floor of the input, element-wise.<br>
Returns largest integer less than or equal to a given number.

In [ ]:
arr = np.array([2.5, 6.3, 4.9, 5.0, 6.8])
np.floor(arr)

### numpy.ceil

Return the ceiling of the input, element-wise.<br>
Return the smallest integer value that is greater than or equal to a number.

In [ ]:
arr = np.array([2.5, 6.3, 4.9, 5.0, 6.8])
np.ceil(arr)

## <font color='orange'> Numpy Linear algebra operations </font>


### numpy.dot()
Computes Dot product of two arrays.


In [ ]:
# If both a and b are 1-D arrays, it is inner product of vectors.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.dot(a= arr1, b= arr2) # (4*1) + (2*5) + (3*6)

In [ ]:
# If both a and b are 2-D arrays, it is matrix multiplication, but using matmul is preferred.
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 5],
                 [4, 8],
                 [4, 1]])

np.dot(a= arr1, b=arr2)

In [ ]:
# If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.
arr1 = np.array([[1, 2],
                 [3, 4]])
x = 4
np.dot(a=arr1, b=x)

In [ ]:
# If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

arr2 = np.array([1,2,3])

np.dot(a= arr1, b= arr2)

### numpy.matmul()
Matrix product of two arrays.

In [ ]:
a = np.array([[1, 0],
              [0, 1]])

b = np.array([[4, 1],
              [2, 2]])

np.matmul(a, b)

### numpy.transpose()
Reverse or permute the axes of an array.<br>
For an array a with two axes, transpose(a) gives the matrix transpose.

In [ ]:
x = np.arange(4).reshape((2,2))
x

In [ ]:
np.transpose(x)

In [ ]:
x = np.ones((1, 2, 3))
x

In [ ]:
x_transposed = np.transpose(x, axes = (1, 0, 2))

print(x_transposed.shape)

x_transposed

## <font color='orange'> Numpy Binary Operations </font>

**Binary Representations-**<br>
33 = 100001 <br>
 1  = 000001    

4 = 100<br>
2 = 010

### numpy.bitwise_or
Compute the bit-wise OR of two arrays element-wise.

In [ ]:
arr1 = np.array([33, 4])
arr2 = np.array([1,  2])

np.bitwise_or(arr1, arr2)

### numpy.bitwise_and
Compute the bit-wise AND of two arrays element-wise.

In [ ]:
arr1 = np.array([33, 4])
arr2 = np.array([1,  2])

np.bitwise_and(arr1, arr2)

## <font color='orange'> Numpy Logic Functions </font>

### numpy.all
Test whether all array elements along a given axis evaluate to True.

In [ ]:
np.all([[True,False],
        [True,True]], axis=0)

### numpy.any
Test whether any array element along a given axis evaluates to True.

In [ ]:
np.any([[True, False],
        [False, False]], axis=0)

### numpy.equal
Return (x1 == x2) element-wise.

In [ ]:
a = np.array([2, 4, 6])

b = np.array([2, 4, 2])

np.equal(a,b)

### numpy.greater
Return the truth value of (x1 > x2) element-wise.

In [ ]:
a = np.array([4, 8, 9])
b = np.array([1, 78, 23])

np.greater(a, b)

## <font color='orange'> Saving and Loading NumPy objects </font>


### numpy.save()
Save an array to a binary file in NumPy .npy format.

In [ ]:
arr1 = np.arange(10)
outfile = 'data/my_arr.npy'

In [ ]:
np.save(file=outfile, arr=arr1)

### numpy.load()
Load arrays from .npy files

In [ ]:
loaded_arr = np.load(file= outfile)
loaded_arr

## <font color='orange'> Miscellaneous </font>


### numpy.sort()

Return a sorted copy of an array.

In [ ]:
arr = np.array([[1,4],
               [3,1]])

np.sort(arr, axis = -1)  # sort along the last axis

### numpy.stack()
Join a sequence of arrays along a new axis.<br>
The axis parameter specifies the index of the new axis in the dimensions of the result.

In [ ]:
arrays = [np.random.randn(3, 4) for i in range(10)]

np.stack(arrays, axis=0).shape

In [ ]:
np.stack(arrays, axis=1).shape

In [ ]:
np.stack(arrays, axis=2).shape

### numpy.hstack()
Stack arrays in sequence horizontally (column wise).

In [ ]:
a = np.array([1,2,3])

b = np.array([4,5,6])

np.hstack((a,b))

In [ ]:
a = np.array([[1],[2],[3]])

b = np.array([[4],[5],[6]])

np.hstack((a,b))

### numpy.vstack()
Stack arrays in sequence vertically (row wise).

In [ ]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

np.vstack((a,b))

In [ ]:
a = np.array([[1], [2], [3]])

b = np.array([[4], [5], [6]])

np.vstack((a,b))

### numpy.squeeze()
Remove axes of length one from array.

In [ ]:
arr = np.array([[1., 2., 3.]])
arr.shape

(1, 3)

In [ ]:
np.squeeze(arr)#.shape

array([1., 2., 3.])

In [ ]:
# If an axis is selected with shape entry greater than one, an error is raised.
np.squeeze(arr, axis=1).shape

### numpy.concatenate()
Join a sequence of arrays along an existing axis.<br>
The arrays must have the same shape, except in the dimension corresponding to axis (the first, by default).

In [ ]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6]])

print(a.shape)
print(b.shape)

np.concatenate((a, b), axis=0)

### numpy.expand_dims()
Expand the shape of an array.<br>

Insert a new axis that will appear at the axis position in the expanded array shape.

In [ ]:
arr = np.array([1, 2])
print(arr.shape)
arr

In [ ]:
expanded_arr = np.expand_dims(arr, axis=0)
print(expanded_arr.shape)
expanded_arr

## <font color='orange'> Integration of OOPS with NumPy </font>

In [ ]:
class NumPyOperations:

    def __init__(self, arr):
        self.arr = arr

    def add(self, array2):
        array_sum = np.add(self.arr, array2)
        return array_sum

    def subtract(self, array2):
        array_sub = np.subtract(self.arr, array2)
        return array_sub

    def multiply(self, array2):
        array_mul = np.multiply(self.arr, array2)
        return array_mul

    def divide(self, array2):
        array_div = np.divide(self.arr, array2)
        return array_div

In [ ]:
arr1 = np.arange(0,10)
obj1 = NumPyOperations(arr1)

In [ ]:
obj1.arr

In [ ]:
arr2 = np.arange(10,20)
obj2 = NumPyOperations(arr2)

In [ ]:
obj1.arr

In [ ]:
obj2.arr

In [ ]:
obj1.add(arr2)

In [ ]:
obj1.subtract(arr2)

In [ ]:
obj1.multiply(arr2)

In [ ]:
obj1.divide(arr2)

### <font color='green'>That's all for Numpy!</font>